name: Build OpenJDK11 for Android

on:
  workflow_dispatch:
  schedule:
  - cron: "20 5 2,9,16,23 * *"

jobs:
  build_android:
    strategy:
      matrix:
        arch: [ "aarch32", "aarch64", "x86", "x86_64" ]
      fail-fast: false

    name: "Build for Android ${{matrix.arch}}"
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1
    - name: set up JDK 11
      uses: actions/setup-java@v4.1.0
      with:
        java-version: 11
        distribution: zulu
    - name: Install build dependencies
      run: |
        sudo apt update
        sudo apt -y install autoconf python unzip zip systemtap-sdt-dev libxtst-dev libasound2-dev libelf-dev libfontconfig1-dev libx11-dev libxext-dev libxrandr-dev libxrender-dev libxtst-dev libxt-dev
        git clone --depth 1 --branch buildjre11 https://github.com/Vera-Firefly/android-openjdk-build
    - name: Build with CI build script
      run: |
        cd android-openjdk-build
        bash "ci_build_arch_${{matrix.arch}}.sh"
    - name: Upload JDK build output
      uses: actions/upload-artifact@v4.3.1
      with:
        name: "jdk11-${{matrix.arch}}"
        path: android-openjdk-build/jdk11*.tar.xz
    - name: Upload JRE build output
      uses: actions/upload-artifact@v4.3.1
      with:
        name: 'jre11-${{matrix.arch}}'
        path: android-openjdk-build/jre11*.tar.xz
    - name: Upload JRE debuginfo build output
      uses: actions/upload-artifact@v4.3.1
      with:
        name: "jre11-debuginfo-${{matrix.arch}}"
        path: android-openjdk-build/dizout

  pojav:
    needs: build_android
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1
    - name: Get jre11-aarch32
      uses: actions/download-artifact@v4.1.4
      with:
        name: jre11-aarch32
        path: pojav
    - name: Get jre11-aarch64
      uses: actions/download-artifact@v4.1.4
      with:
        name: jre11-aarch64
        path: pojav
    - name: Get jre11-x86
      uses: actions/download-artifact@v4.1.4
      with:
        name: jre11-x86
        path: pojav
    - name: Get jre11-x86_64
      uses: actions/download-artifact@v4.1.4
      with:
        name: jre11-x86_64
        path: pojav
    - name: Repack JRE
      run: |
        git clone --depth 1 --branch buildjre11 https://github.com/Vera-Firefly/android-openjdk-build
        bash "android-openjdk-build/repackjre.sh" $GITHUB_WORKSPACE/pojav $GITHUB_WORKSPACE/pojav/jre11-pojav
    - name: Upload artifact
      uses: actions/upload-artifact@v4.3.1
      with:
          name: jre11-pojav
          path: pojav/jre11-pojav/*

  push:
    if: github.repository_owner == 'Vera-Firefly' && github.ref_name == 'push'
    needs: pojav
    runs-on: ubuntu-latest
    steps:
    - name: Set IS_MAIN_BRANCH if on main branch
      run: echo "JRE_OUTPUT=11" >> $GITHUB_ENV

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get jre
      uses: actions/download-artifact@v4.1.7
      with:
        name: jre11-pojav
        path: JreOutPut

    - name: Push New Jre on this Repository
      run: |
        chmod +x push.sh
        sh push.sh
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_KEY_PASSWORD: ${{ secrets.SSH_KEY_PASSWORD }}
        USER_EMAIL: ${{ secrets.USER_EMAIL }}
        USER_NAME: ${{ secrets.USER_NAME }}
      shell: bash

